// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func inject() *Foo {
	slice01 := provideBars()
	slice02 := provideBarsAgain()
	v := slice01
	v = append(v, slice02...)
	baaz := &Baaz{
		bars: v,
	}
	foo := provideFoo(baaz, v...)
	return foo
}

func injectSingle() *Foo {
	v := provideBars()
	baaz := &Baaz{
		bars: v,
	}
	foo := provideFoo(baaz, v...)
	return foo
}

func injectWithGiven(bars []*Bar) *Foo {
	slice04 := provideBars()
	slice05 := provideBarsAgain()
	v := bars
	v = append(v, slice04...)
	v = append(v, slice05...)
	baaz := &Baaz{
		bars: v,
	}
	foo := provideFoo(baaz, v...)
	return foo
}
